# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '8e427625-a5ca-4f8d-9e2d-0440c0d9b3f0'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'North Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/ltueki/AzureRmPipeline-repo/main/CreateWebApp/azuredeployaks.json'
    overrideParameters: '-projectName sac231101'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'